apiVersion: cloud.crate.io/v1
kind: CrateDB
metadata:
  name: {{ include "finops-cratedb-cluster-chart.fullname" . }}
spec:
  cluster:
    name: {{ finops-cratedb-cluster-chart.fullname }}
    imageRegistry: {{ .Values.image.repository }}
    version: {{ .Values.image.tag | default .Chart.AppVersion }}
  nodes:
    data:
    - name: {{ .Values.nodeName }}
      replicas: {{ .Values.replicaCount }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}