apiVersion: cloud.crate.io/v1
kind: CrateDB
metadata:
  name: {{ include "finops-cratedb-cluster-chart.name" . }}
spec:
  cluster:
    imageRegistry: {{ .Values.image.repository }}
    name: {{ .Values.fullNameOverride | default .Release.Name }}
    version: {{ .Values.image.tag | default .Chart.AppVersion }}
  nodes:
    data:
    - name: node
      replicas: {{ .Values.replicaCount }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}